apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-perf-test
  namespace: default
spec:
  containers:
    - name: perf-test
      image: pivotalrabbitmq/perf-test:latest
      command:
        - "sh"
        - "-c"
        - |
          java -jar perf-test.jar --uri "amqp://test:test@import-definitions-v3.default.svc:5672" --queue-pattern 'qq%d' --queue-pattern-from 1 --queue-pattern-to 5000 --producers 15 -f persistent -s 400
