apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: my-rabbitmq-cluster
  namespaceSelector:
    matchNames:
    - rabbitmq
  podMetricsEndpoints:
  - port: prometheus
    interval: 30s
    path: /metrics
