apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-kafka
  namespace: strimzi
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  namespaceSelector:
    matchNames:
    - strimzi
  podMetricsEndpoints:
  - port: tcp-prometheus
    interval: 30s
    path: /metrics
