apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-entity-operator-pods
  namespace: strimzi
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: entity-operator
  namespaceSelector:
    matchNames:
      - strimzi
  podMetricsEndpoints:
    - port: healthcheck
      interval: 30s
      path: /metrics
