apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-zookeeper
  namespace: strimzi
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
  namespaceSelector:
    matchNames:
    - strimzi
  podMetricsEndpoints:
  - port: tcp-prometheus
    interval: 30s
    path: /metrics
