apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: strimzi-zookeeper
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
  namespaceSelector:
    matchNames:
    - strimzi
  endpoints:
  - port: tcp-prometheus
    interval: 30s
