apiVersion: batch/v1
kind: Job
metadata:
  name: traces-generator-job
spec:
  template:
    metadata:
      labels:
        app: traces-generator-job
    spec:
      containers:
      - name: traces-generator
        image: public.ecr.aws/prequel-dev/workshop/traces-generator:latest
        env:
        - name: COLLECTOR_ADDRESS
          value: "otel-collector.monitoring.svc.cluster.local:14268"
        - name: TRACES_PER_WORKER
          value: "50"
        - name: NUM_WORKERS
          value: "4"
      restartPolicy: Never
  backoffLimit: 0
