apiVersion: batch/v1
kind: Job
metadata:
  name: messages-generator-job
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      labels:
        app: messages-generator-job
    spec:
      restartPolicy: Never
      containers:
      - name: messages-generator
        image: public.ecr.aws/prequel-dev/workshop/messages-generator:latest
        env:
        - name: RMQ_ADDRESS
          value: "my-rabbitmq-cluster.rabbitmq.svc.cluster.local:5673"